# Generated by Django 4.2.10 on 2024-05-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, default='default_background/default5.png', null=True, upload_to='backgroundPics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_icon/default5.png', null=True, upload_to='profilePics'),
        ),
    ]
